package leetcode;

/*
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 */

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        
    	int[] ai = new int[26];
    	
    	for (char ch : s.toCharArray()) {
    		ai[ch - 'a']++;
    	}
    	
    	for (char ch : t.toCharArray()) {
    		ai[ch - 'a']--;
    	}
    	for (int i = 0; i < 26; ++i) {
    		if (ai[i] < 0)
    			return (char) (i + 'a');
    	}
    	
    	return 0;
    }
}
